"""
Test coverage mapper — Week 7.

Strategy:
  1. Primary: read .coverage SQLite file (generated by pytest --cov).
     Uses coverage.py API to get exact line-level coverage per file.
  2. Fallback: convention-based mapping.
     test_auth.py → auth.py, tests/test_payment.py → src/payment.py

For each file in blast_radius, determines:
  - is_covered: True if at least one test covers this file
  - covering_tests: list of test files that import/cover this file
  - coverage_gap: list of files with no test coverage
"""

import re
from pathlib import Path


# ---------------------------------------------------------------------------
# Primary: .coverage file (coverage.py SQLite format)
# ---------------------------------------------------------------------------

def read_coverage_file(coverage_path: str | Path) -> dict[str, list[str]]:
    """
    Parse .coverage SQLite file and return mapping:
        source_file → [list of test files that cover it]

    Requires: coverage.py installed (already in requirements via pytest-cov).
    Falls back to empty dict if file not found or unreadable.
    """
    import sqlite3

    coverage_path = Path(coverage_path)
    if not coverage_path.exists():
        return {}

    try:
        conn = sqlite3.connect(str(coverage_path))
        # .coverage schema: file table + line_bits table
        # arc/line_bits table maps file_id → measured lines
        files = {
            row[0]: row[1]
            for row in conn.execute("SELECT id, path FROM file").fetchall()
        }
        # Which files have any coverage data (i.e. were executed)
        covered_ids = set(
            row[0]
            for row in conn.execute("SELECT DISTINCT file_id FROM line_bits").fetchall()
        )
        conn.close()

        # source_files = files measured by coverage that have any line data
        # (i.e. were actually executed during test run)
        covered_source_files = {
            files[fid] for fid in covered_ids
            if fid in files and not _is_test_file(files[fid])
        }

        # Build source → [test_files] using convention mapping
        # coverage.py without --cov-context doesn't give per-test attribution
        result: dict[str, list[str]] = {}
        for src in covered_source_files:
            stem = Path(src).stem
            # Look for test_<stem>.py anywhere in the repo parent
            repo_parent = Path(src).parent.parent  # e.g. dummy_repo/
            test_candidates = (
                list(repo_parent.rglob(f"test_{stem}.py")) +
                list(repo_parent.rglob(f"{stem}_test.py"))
            )
            result[src] = [str(t) for t in test_candidates]

        return result

    except Exception:
        return {}


# ---------------------------------------------------------------------------
# Fallback: convention-based mapping
# ---------------------------------------------------------------------------

def convention_map(
    repo_root: str | Path,
    source_files: list[str],
) -> dict[str, list[str]]:
    """
    Map source files → test files using naming convention.
    Searches for test files matching test_<name>.py or <name>_test.py.

    Returns: source_file → [test_files]
    """
    repo_root = Path(repo_root)
    all_test_files = list(repo_root.rglob("test_*.py")) + list(repo_root.rglob("*_test.py"))

    result: dict[str, list[str]] = {}
    for src in source_files:
        src_path = Path(src)
        stem = src_path.stem  # e.g. "auth" from "auth.py"
        matches = [
            str(t) for t in all_test_files
            if t.stem in (f"test_{stem}", f"{stem}_test")
        ]
        result[src] = matches

    return result


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def compute_coverage_gap(
    blast_radius_files: list[str],
    repo_root: str | Path,
    coverage_file: str | Path | None = None,
) -> dict:
    """
    For each file in blast_radius_files, determine if it has test coverage.

    Args:
        blast_radius_files: absolute or relative file paths from KG impact query
        repo_root: root of the repository
        coverage_file: path to .coverage file (optional)

    Returns dict:
        covered:       {file: [test_files]}
        uncovered:     [files with no test coverage]
        coverage_gap_ratio: len(uncovered) / len(blast_radius_files)
        method:        "coverage_file" | "convention"
    """
    repo_root = Path(repo_root)

    # Only consider Python source files (skip __init__.py, test files)
    source_files = [
        f for f in blast_radius_files
        if f.endswith(".py") and not _is_test_file(f) and "__init__" not in f
    ]

    if not source_files:
        return {
            "covered": {},
            "uncovered": [],
            "coverage_gap_ratio": 0.0,
            "method": "none",
        }

    coverage_map: dict[str, list[str]] = {}
    method = "convention"

    # Try primary: .coverage file
    if coverage_file is None:
        coverage_file = repo_root / ".coverage"

    cov_data = read_coverage_file(coverage_file)
    if cov_data:
        method = "coverage_file"
        # Match blast radius files against coverage data (normalize paths)
        for src in source_files:
            src_norm = _normalize(src)
            match = next(
                (k for k in cov_data if _normalize(k) == src_norm), None
            )
            coverage_map[src] = cov_data.get(match, []) if match else []
    else:
        # Fallback: convention
        coverage_map = convention_map(repo_root, source_files)

    covered = {f: tests for f, tests in coverage_map.items() if tests}
    uncovered = [f for f, tests in coverage_map.items() if not tests]
    total = len(source_files)
    gap_ratio = len(uncovered) / total if total > 0 else 0.0

    return {
        "covered": covered,
        "uncovered": uncovered,
        "coverage_gap_ratio": round(gap_ratio, 3),
        "method": method,
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_test_file(path: str) -> bool:
    name = Path(path).name
    return name.startswith("test_") or name.endswith("_test.py")


def _normalize(path: str) -> str:
    return Path(path).as_posix().lower()


def _guess_source_from_test(test_file: str, source_files: set[str]) -> str | None:
    """Given test_auth.py, find auth.py in source_files."""
    stem = Path(test_file).stem  # test_auth
    source_stem = re.sub(r"^test_|_test$", "", stem)  # auth
    return next(
        (s for s in source_files if Path(s).stem == source_stem), None
    )
